config/routes.rb
Costrecovery::Application.routes.draw do
   
  

  

  root :to => "incidents#index"
  
  resources :users
  resources :profiles
  
  resources :incidents do
    
    resource :mat_list
	member do
	post :send_notice
	end
	member do
	get :changestatus
	end

	
	
	resource :timesheet do
	    resources :command_officers
		resources :fire_chiefs
		resources :fire_fighters
		resources :safety_officers
		resources :emts
		resources :hazmat_specialists
		resources :command_vehicles
		resources :engines
		resources :emergency_supports
		resources :hazmat_units
		resources :field_units
		resources :pumpers
		resources :tankers
		resources :rescue_units
		resources :ladder_truck75s
		resources :ladder_truck150s
	end
  end
  	
   
  resource :session do
  member do
  get :resetpass
  post :resetpass
  end
  end
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/fire_fighter.rb
class FireFighter < ActiveRecord::Base
	belongs_to :timesheet
	
	validates :name, :presence => true
	validates :first_hour, :additional_hours, :total_hours, :hazmat_hours, :numericality => true
	
	def totalamount
		a = first_hour * rate1
		b = additional_hours * rate2
		a + b
	end
	
	def rate1
		50
	end
	
	def rate2
		75
	end
end

app/controllers/fire_fighters_controller.rb
class FireFightersController < ApplicationController
 
  # GET /fire_fighters/1
  # GET /fire_fighters/1.xml
  #def show
   # @fire_fighter = FireFighter.find(params[:id])

   # respond_to do |format|
   #   format.html # show.html.erb
   #   format.xml  { render :xml => @fire_fighter }
   # end
  #end

  # GET /fire_fighters/new
  # GET /fire_fighters/new.xml
  def new
    @fire_fighter = FireFighter.new
	@timesheet = Incident.find(params[:incident_id]).timesheet

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fire_fighter }
    end
  end

  # GET /fire_fighters/1/edit
  def edit
    @fire_fighter = FireFighter.find(params[:id])
 end

  # POST /fire_fighters
  # POST /fire_fighters.xml
  def create
    @timesheet = Incident.find(params[:incident_id]).timesheet
	@fire_fighter = @timesheet.fire_fighters.build(params[:fire_fighter])

    respond_to do |format|
      if @fire_fighter.save
        format.html { redirect_to(edit_incident_timesheet_path, :notice => 'Fire Fighter was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /fire_fighters/1
  # PUT /fire_fighters/1.xml
  def update
    @fire_fighter = FireFighter.find(params[:id])

    respond_to do |format|
      if @fire_fighter.update_attributes(params[:fire_fighter])
        format.html { redirect_to(incident_timesheet_path, :notice => 'Fire fighter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fire_fighter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fire_fighters/1
  # DELETE /fire_fighters/1.xml
  def destroy
    @fire_fighter = FireFighter.find(params[:id])
    @fire_fighter.destroy

    respond_to do |format|
      format.html { redirect_to(incident_timesheet_path, :notice => 'Fire Fighter was successfully deleted.') }
    end
  end
end

app/helpers/fire_fighters_helper.rb
module FireFightersHelper
end

app/views/fire_fighters/_editform.html.erb
<%= form_for @fire_fighter, :url => { :action => "update" }, :html => { :method => :put } do |f| %>
  <% if @fire_fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fire_fighter.errors.count, "error") %> prohibited this fire_fighter from being saved:</h2>
      <ul>
      <% @fire_fighter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %> <br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %> <br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %> <br />
    <%= f.text_field :hazmat_hours %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fire_fighters/_form.html.erb
<%= form_for @fire_fighter, :url => { :action => "create" } do |f| %>
  <% if @fire_fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fire_fighter.errors.count, "error") %> prohibited this fire_fighter from being saved:</h2>

      <ul>
      <% @fire_fighter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
  <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %><br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %><br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %><br />
    <%= f.text_field :hazmat_hours %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fire_fighters/edit.html.erb
<%= link_to 'Cancel', incident_timesheet_path %>

<h1>Edit Fire Fighter</h1>

<%= render 'editform' %>

app/views/fire_fighters/new.html.erb
<%= link_to 'Back To Timesheet', edit_incident_timesheet_path %>

<h1>Add a Fire Fighter</h1>

<%= render 'form' %>

app/views/fire_fighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fire_fighter.name %>
</p>

<p>
  <b>First hour:</b>
  <%= @fire_fighter.first_hour %>
</p>

<p>
  <b>Additional hours:</b>
  <%= @fire_fighter.additional_hours %>
</p>

<p>
  <b>Total hours:</b>
  <%= @fire_fighter.total_hours %>
</p>

<p>
  <b>Hazmat hours:</b>
  <%= @fire_fighter.hazmat_hours %>
</p>

<p>
  <b>Rate1:</b>
  <%= @fire_fighter.rate1 %>
</p>

<p>
  <b>Rate2:</b>
  <%= @fire_fighter.rate2 %>
</p>


<%= link_to 'Edit', edit_fire_fighter_path(@fire_fighter) %> |
<%= link_to 'Back', fire_fighters_path %>