config/routes.rb
Costrecovery::Application.routes.draw do
   
  

  

  root :to => "incidents#index"
  
  resources :users
  resources :profiles
  
  resources :incidents do
    
    resource :mat_list
	member do
	post :send_notice
	end
	member do
	get :changestatus
	end

	
	
	resource :timesheet do
	    resources :command_officers
		resources :fire_chiefs
		resources :fire_fighters
		resources :safety_officers
		resources :emts
		resources :hazmat_specialists
		resources :command_vehicles
		resources :engines
		resources :emergency_supports
		resources :hazmat_units
		resources :field_units
		resources :pumpers
		resources :tankers
		resources :rescue_units
		resources :ladder_truck75s
		resources :ladder_truck150s
	end
  end
  	
   
  resource :session do
  member do
  get :resetpass
  post :resetpass
  end
  end
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/tanker.rb
class Tanker < ActiveRecord::Base
	belongs_to :timesheet
	
	validates :name, :presence => true
	validates :first_hour, :additional_hours, :total_hours, :hazmat_hours, :numericality => true
	
	def totalamount
		a = first_hour * rate1
		b = additional_hours * rate2
		a + b
	end
	
	def rate1
		360
	end
	
	def rate2
		480
	end
end

app/controllers/tankers_controller.rb
class TankersController < ApplicationController
  # GET /tankers
  # GET /tankers.xml
 
  # GET /tankers/1
  # GET /tankers/1.xml
#  def show
 #   @tanker = Tanker.find(params[:id])

  #  respond_to do |format|
   #   format.html # show.html.erb
    #  format.xml  { render :xml => @tanker }
   # end
 # end

  # GET /tankers/new
  # GET /tankers/new.xml
  def new
    @tanker = Tanker.new
	@timesheet = Incident.find(params[:incident_id]).timesheet

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tanker }
    end
  end

  # GET /tankers/1/edit
  def edit
    @tanker = Tanker.find(params[:id])
  end

  # POST /tankers
  # POST /tankers.xml
  def create
    @timesheet = Incident.find(params[:incident_id]).timesheet
	@tanker = @timesheet.tankers.build(params[:tanker])

    respond_to do |format|
      if @tanker.save
        format.html { redirect_to(edit_incident_timesheet_path, :notice => 'Tanker was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /tankers/1
  # PUT /tankers/1.xml
  def update
    @tanker = Tanker.find(params[:id])

    respond_to do |format|
      if @tanker.update_attributes(params[:tanker])
        format.html { redirect_to(incident_timesheet_path, :notice => 'Tanker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tanker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tankers/1
  # DELETE /tankers/1.xml
  def destroy
    @tanker = Tanker.find(params[:id])
    @tanker.destroy

    respond_to do |format|
      format.html { redirect_to(incident_timesheet_path, :notice => 'Tanker was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tankers_helper.rb
module TankersHelper
end

app/views/tankers/_editform.html.erb
<%= form_for @tanker, :url => { :action => "update" }, :html => { :method => :put } do |f| %>
  <% if @tanker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tanker.errors.count, "error") %> prohibited this tanker from being saved:</h2>
      <ul>
      <% @tanker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %> <br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %> <br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %> <br />
    <%= f.text_field :hazmat_hours %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tankers/_form.html.erb
<%= form_for @tanker, :url => { :action => "create" } do |f| %>
  <% if @tanker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tanker.errors.count, "error") %> prohibited this tanker from being saved:</h2>

      <ul>
      <% @tanker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %><br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %><br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %><br />
    <%= f.text_field :hazmat_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tankers/edit.html.erb
<%= link_to 'Cancel', incident_timesheet_path %>

<h1>Edit Tanker</h1>

<%= render 'editform' %>

app/views/tankers/new.html.erb
<%= link_to 'Back To Timesheet', edit_incident_timesheet_path %>

<h1>Add a Tanker</h1>

<%= render 'form' %>

app/views/tankers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tanker.name %>
</p>

<p>
  <b>First hour:</b>
  <%= @tanker.first_hour %>
</p>

<p>
  <b>Additional hours:</b>
  <%= @tanker.additional_hours %>
</p>

<p>
  <b>Total hours:</b>
  <%= @tanker.total_hours %>
</p>

<p>
  <b>Hazmat hours:</b>
  <%= @tanker.hazmat_hours %>
</p>

<p>
  <b>Rate1:</b>
  <%= @tanker.rate1 %>
</p>

<p>
  <b>Rate2:</b>
  <%= @tanker.rate2 %>
</p>


<%= link_to 'Edit', edit_tanker_path(@tanker) %> |
<%= link_to 'Back', tankers_path %>