config/routes.rb
Costrecovery::Application.routes.draw do
   
  

  

  root :to => "incidents#index"
  
  resources :users
  resources :profiles
  
  resources :incidents do
    
    resource :mat_list
	member do
	post :send_notice
	end
	member do
	get :changestatus
	end

	
	
	resource :timesheet do
	    resources :command_officers
		resources :fire_chiefs
		resources :fire_fighters
		resources :safety_officers
		resources :emts
		resources :hazmat_specialists
		resources :command_vehicles
		resources :engines
		resources :emergency_supports
		resources :hazmat_units
		resources :field_units
		resources :pumpers
		resources :tankers
		resources :rescue_units
		resources :ladder_truck75s
		resources :ladder_truck150s
	end
  end
  	
   
  resource :session do
  member do
  get :resetpass
  post :resetpass
  end
  end
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/hazmat_specialist.rb
class HazmatSpecialist < ActiveRecord::Base
	belongs_to :timesheet
	
	validates :name, :presence => true
	validates :first_hour, :additional_hours, :total_hours, :hazmat_hours, :numericality => true
	
	def totalamount
		a = first_hour * rate1
		b = additional_hours * rate2
		a + b
	end
	
	def rate1
		75
	end
	
	def rate2
		125
	end
end

app/controllers/hazmat_specialists_controller.rb
class HazmatSpecialistsController < ApplicationController
  # GET /hazmat_specialists
  # GET /hazmat_specialists.xml
 

  # GET /hazmat_specialists/1
  # GET /hazmat_specialists/1.xml
 # def show
  #  @hazmat_specialist = HazmatSpecialist.find(params[:id])

   # respond_to do |format|
    #  format.html # show.html.erb
     # format.xml  { render :xml => @hazmat_specialist }
   # end
 # end

  # GET /hazmat_specialists/new
  # GET /hazmat_specialists/new.xml
  def new
    @hazmat_specialist = HazmatSpecialist.new
    @timesheet = Incident.find(params[:incident_id]).timesheet
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hazmat_specialist }
    end
  end

  # GET /hazmat_specialists/1/edit
  def edit
    @hazmat_specialist = HazmatSpecialist.find(params[:id])
  end

  # POST /hazmat_specialists
  # POST /hazmat_specialists.xml
  def create
    @timesheet = Incident.find(params[:incident_id]).timesheet
	@hazmat_specialist = @timesheet.hazmat_specialists.build(params[:hazmat_specialist])

    respond_to do |format|
      if @hazmat_specialist.save
        format.html { redirect_to(edit_incident_timesheet_path, :notice => 'Hazmat Specialist was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /hazmat_specialists/1
  # PUT /hazmat_specialists/1.xml
  def update
    @hazmat_specialist = HazmatSpecialist.find(params[:id])

    respond_to do |format|
      if @hazmat_specialist.update_attributes(params[:hazmat_specialist])
        format.html { redirect_to(incident_timesheet_path, :notice => 'Hazmat specialist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hazmat_specialist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hazmat_specialists/1
  # DELETE /hazmat_specialists/1.xml
  def destroy
    @hazmat_specialist = HazmatSpecialist.find(params[:id])
    @hazmat_specialist.destroy

    respond_to do |format|
      format.html { redirect_to(incident_timesheet_path, :notice => 'Hazmat Specialist was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/hazmat_specialists_helper.rb
module HazmatSpecialistsHelper
end

app/views/hazmat_specialists/_editform.html.erb
<%= form_for @hazmat_specialist, :url => { :action => "update" }, :html => { :method => :put } do |f| %>
  <% if @hazmat_specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hazmat_specialist.errors.count, "error") %> prohibited this hazmat_specialist from being saved:</h2>
      <ul>
      <% @hazmat_specialist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %> <br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %> <br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %> <br />
    <%= f.text_field :hazmat_hours %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hazmat_specialists/_form.html.erb
<%= form_for @hazmat_specialist, :url => { :action => "create" } do |f| %>
  <% if @hazmat_specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hazmat_specialist.errors.count, "error") %> prohibited this hazmat_specialist from being saved:</h2>

      <ul>
      <% @hazmat_specialist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %><br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %><br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %><br />
    <%= f.text_field :hazmat_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hazmat_specialists/edit.html.erb
<%= link_to 'Cancel', incident_timesheet_path %>

<h1>Edit HazMat Specialist</h1>

<%= render 'editform' %>

app/views/hazmat_specialists/new.html.erb
<%= link_to 'Back To Timesheet', edit_incident_timesheet_path %>

<h1>Add a Hazmat Specialist</h1>

<%= render 'form' %>

app/views/hazmat_specialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hazmat_specialist.name %>
</p>

<p>
  <b>First hour:</b>
  <%= @hazmat_specialist.first_hour %>
</p>

<p>
  <b>Additional hours:</b>
  <%= @hazmat_specialist.additional_hours %>
</p>

<p>
  <b>Total hours:</b>
  <%= @hazmat_specialist.total_hours %>
</p>

<p>
  <b>Hazmat hours:</b>
  <%= @hazmat_specialist.hazmat_hours %>
</p>

<p>
  <b>Rate1:</b>
  <%= @hazmat_specialist.rate1 %>
</p>

<p>
  <b>Rate2:</b>
  <%= @hazmat_specialist.rate2 %>
</p>


<%= link_to 'Edit', edit_hazmat_specialist_path(@hazmat_specialist) %> |
<%= link_to 'Back', hazmat_specialists_path %>