config/routes.rb
Costrecovery::Application.routes.draw do
   
  

  

  root :to => "incidents#index"
  
  resources :users
  resources :profiles
  
  resources :incidents do
    
    resource :mat_list
	member do
	post :send_notice
	end
	member do
	get :changestatus
	end

	
	
	resource :timesheet do
	    resources :command_officers
		resources :fire_chiefs
		resources :fire_fighters
		resources :safety_officers
		resources :emts
		resources :hazmat_specialists
		resources :command_vehicles
		resources :engines
		resources :emergency_supports
		resources :hazmat_units
		resources :field_units
		resources :pumpers
		resources :tankers
		resources :rescue_units
		resources :ladder_truck75s
		resources :ladder_truck150s
	end
  end
  	
   
  resource :session do
  member do
  get :resetpass
  post :resetpass
  end
  end
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/rescue_unit.rb
class RescueUnit < ActiveRecord::Base
	belongs_to :timesheet
	
	validates :name, :presence => true
	validates :first_hour, :additional_hours, :total_hours, :hazmat_hours, :numericality => true
	
	def totalamount
		a = first_hour * rate1
		b = additional_hours * rate2
		a + b
	end
	
	def rate1
		360
	end
	
	def rate2
		480
	end
end

app/controllers/rescue_units_controller.rb
class RescueUnitsController < ApplicationController
  # GET /rescue_units
  # GET /rescue_units.xml
  

  # GET /rescue_units/1
  # GET /rescue_units/1.xml
 # def show
  #  @rescue_unit = RescueUnit.find(params[:id])

   # respond_to do |format|
    #  format.html # show.html.erb
     # format.xml  { render :xml => @rescue_unit }
   # end
 # end

  # GET /rescue_units/new
  # GET /rescue_units/new.xml
  def new
    @rescue_unit = RescueUnit.new
    @timesheet = Incident.find(params[:incident_id]).timesheet
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rescue_unit }
    end
  end

  # GET /rescue_units/1/edit
  def edit
    @rescue_unit = RescueUnit.find(params[:id])
  end

  # POST /rescue_units
  # POST /rescue_units.xml
  def create
    @timesheet = Incident.find(params[:incident_id]).timesheet
	@rescue_unit = @timesheet.rescue_units.build(params[:rescue_unit])

    respond_to do |format|
      if @rescue_unit.save
        format.html { redirect_to(edit_incident_timesheet_path, :notice => 'Rescue Unit was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /rescue_units/1
  # PUT /rescue_units/1.xml
  def update
    @rescue_unit = RescueUnit.find(params[:id])

    respond_to do |format|
      if @rescue_unit.update_attributes(params[:rescue_unit])
        format.html { redirect_to(incident_timesheet_path, :notice => 'Rescue unit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rescue_unit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rescue_units/1
  # DELETE /rescue_units/1.xml
  def destroy
    @rescue_unit = RescueUnit.find(params[:id])
    @rescue_unit.destroy

    respond_to do |format|
      format.html { redirect_to(incident_timesheet_path, :notice => 'Rescue Unit was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rescue_units_helper.rb
module RescueUnitsHelper
end

app/views/rescue_units/_editform.html.erb
<%= form_for @rescue_unit, :url => { :action => "update" }, :html => { :method => :put } do |f| %>
  <% if @rescue_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rescue_unit.errors.count, "error") %> prohibited this rescue_unit from being saved:</h2>
      <ul>
      <% @rescue_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %> <br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %> <br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %> <br />
    <%= f.text_field :hazmat_hours %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rescue_units/_form.html.erb
<%= form_for @rescue_unit, :url => { :action => "create" } do |f| %>
  <% if @rescue_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rescue_unit.errors.count, "error") %> prohibited this rescue_unit from being saved:</h2>

      <ul>
      <% @rescue_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<hr />
 <p><strong><font color="red">IMPORTANT</font></strong>: Enter time on scene in hours (0.25 = fifteen minutes, 0.5 = half hour, 1 = one hour, etc.)</p>
  <hr />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_hour %> <font color="#666">(0.25 = fifteen minutes, 0.5 = half hour, etc.)</font><br />
    <%= f.text_field :first_hour %>
  </div>
  <div class="field">
    <%= f.label :additional_hours %><br />
    <%= f.text_field :additional_hours %>
  </div>
  <div class="field">
    <%= f.label :total_hours %><br />
    <%= f.text_field :total_hours %>
  </div>
  <div class="field">
    <%= f.label :hazmat_hours %><br />
    <%= f.text_field :hazmat_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rescue_units/edit.html.erb
<%= link_to 'Cancel', incident_timesheet_path %>

<h1>Edit Rescue Unit</h1>

<%= render 'editform' %>

app/views/rescue_units/new.html.erb
<%= link_to 'Back To Timesheet', edit_incident_timesheet_path %>

<h1>Add a Rescue Unit</h1>

<%= render 'form' %>

app/views/rescue_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rescue_unit.name %>
</p>

<p>
  <b>First hour:</b>
  <%= @rescue_unit.first_hour %>
</p>

<p>
  <b>Additional hours:</b>
  <%= @rescue_unit.additional_hours %>
</p>

<p>
  <b>Total hours:</b>
  <%= @rescue_unit.total_hours %>
</p>

<p>
  <b>Hazmat hours:</b>
  <%= @rescue_unit.hazmat_hours %>
</p>

<p>
  <b>Rate1:</b>
  <%= @rescue_unit.rate1 %>
</p>

<p>
  <b>Rate2:</b>
  <%= @rescue_unit.rate2 %>
</p>


<%= link_to 'Edit', edit_rescue_unit_path(@rescue_unit) %> |
<%= link_to 'Back', rescue_units_path %>